### ISSUE TITLE
Как использовать?

### ISSUE THREAD

**Issue by vwscripts** [Frago9876543210/hikvision-bruteforcer#1]
?)

**Comment by Frago9876543210** [comment]
Достать каким-то образом диапазоны IP одного города или страны, просканить их по портам 8000, 8001, 8002 (я встречал камеры, которые работают с 8000 до 8009). Еще есть порт 37777, но там камеры другого типа. Далее скачать последний билд: https://github.com/Frago9876543210/hikvision-bruteforcer/releases. Потом закинуть ип в data/IPs.txt и можно начинать брут.

**Comment by Frago9876543210** [comment]
Если что-то не понимаешь, то напиши мне в вк.

**Comment by ivan691** [comment]
Я знаю это, но хз как и через что запустить брут.
